/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistamenu;

import conexion.ConexionBD;
import controlador.FilmDAO;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Film;

/**
 *
 * @author Miguel
 */
public class FilmMenu extends javax.swing.JFrame {
    Connection con;
    CallableStatement cs;
    static ResultSet rs;
     int cont;

    /**
     * Creates new form Film
     */
    public FilmMenu() {
        initComponents();
        cargarPeliculas();
        this.setLocationRelativeTo(null);
        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilm = new javax.swing.JTable();
        txtB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cmbl1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cml2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbCla = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbCat = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("REGRESAR");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, 160, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTROS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Descripción", "Fecha Estreno", "Idioma", "Idioma Original", "Duración", "Costo", "Clasificasión", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilm);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 270));

        txtB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBKeyReleased(evt);
            }
        });
        jPanel1.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 220, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("BUSCAR:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 750, 450));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtTit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitActionPerformed(evt);
            }
        });
        jPanel2.add(txtTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 287, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel2.add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 280, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lenguaje:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        cmbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbl1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Idioma...", "English", "Italian", "Japanese", "Mandarin", "French", "German" }));
        jPanel2.add(cmbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lenguaje Original:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        cml2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cml2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Idioma...", "English", "Italian", "Japanese", "Mandarin", "French", "German" }));
        jPanel2.add(cml2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duración:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtDura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuraActionPerformed(evt);
            }
        });
        txtDura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDuraKeyReleased(evt);
            }
        });
        jPanel2.add(txtDura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Costo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txtCos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clasificación:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        cmbCla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "G", "PG", "PG-13", "R", "NC-17" }));
        jPanel2.add(cmbCla, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 200, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Categoría:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        cmbCat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "Action", "Animation", "Children", "Classics", "Comedy", "Documentary", "Drama", "Family", "Foreign", "Games", "Horror", "Music", "New", "Sci-Fi", "Sports", "Travel" }));
        jPanel2.add(cmbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Minutos");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 70, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("$");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        info2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 520));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GUARDAR");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFICAR");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 150, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 130, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 530, 110));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fond2.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(txtTit.getText().isEmpty()||txtDesc.getText().equals("") || cmbl1.getSelectedIndex()==0 || cml2.getSelectedIndex()==0 || txtDura.getText().equals("")
                || txtCos.getText().equals("")|| cmbCla.getSelectedIndex()==0|| cmbCat.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Ingrese los datos Correctamente", "Error", JOptionPane.ERROR_MESSAGE);
            
        } else {
            rs =conexion.ConexionBD.Consulta("SELECT COUNT(title) FROM film WHERE title= '"+ txtTit.getText()+ "'");
            try {
                while(rs.next()){
                    cont = rs.getInt(1);
                }
                    
            } catch (SQLException e) {
            }
            if(cont >= 1){
                JOptionPane.showMessageDialog(this, "Esta Pelicula Ya esta en La BASE DE DATOS","Informacion",JOptionPane.INFORMATION_MESSAGE);
            } else{
                ConexionBD cc= new ConexionBD();
                Connection cn = cc.getConnection();
                try {
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO film(title,description,release_year,language_name, "
                            + "original_language_name ,length,cost,rating,category_name) VALUES (?,?,?,?,?,?,?,?,?)");
                    pst.setString(1, txtTit.getText());
                    pst.setString(2, txtDesc.getText());
                    pst.setDate(3, new java.sql.Date(cal.getDate().getTime()));
                    pst.setString(4,String.valueOf(cmbl1.getSelectedItem()));
                    pst.setString(5,String.valueOf(cml2.getSelectedItem()));
                    pst.setInt(6, Integer.parseInt(txtDura.getText()));
                    pst.setDouble(7, Double.parseDouble(txtCos.getText()));
                    pst.setString(8,String.valueOf(cmbCla.getSelectedItem()));
                    pst.setString(9,String.valueOf(cmbCat.getSelectedItem()));
                    
                    pst.executeUpdate();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(FilmMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "LOS DATOS SE REGISTRARON CORRECTAMENTE");
                txtTit.setText("");
                txtDesc.setText("");
                cmbl1.setSelectedIndex(0);
                cml2.setSelectedIndex(0);
                txtDura.setText("");
                txtCos.setText("");
                cmbCla.setSelectedIndex(0);
                cmbCat.setSelectedIndex(0);
                
            }
       }
        cargarPeliculas();
            
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuraActionPerformed

    private void txtTitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      if(txtTit.getText().isEmpty()||txtDesc.getText().equals("") || cmbl1.getSelectedIndex()==0 || cml2.getSelectedIndex()==0 || txtDura.getText().equals("") 
              || txtCos.getText().equals("")|| cmbCla.getSelectedIndex()==0|| cmbCat.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(getParent(), " LLENAR DATOS", "AVISO", JOptionPane.INFORMATION_MESSAGE);				 
        }else {
           
                int opcion = JOptionPane.showConfirmDialog(null, "¿DESEA MODIFICAR EL REGISTRO?", "AVISO", JOptionPane.WARNING_MESSAGE);
		if(opcion == JOptionPane.YES_OPTION){
                    
                      try {
                        boolean res = new FilmDAO().modificarfilm(new  Film(Integer.parseInt(txtId.getText()), txtTit.getText(), txtDesc.getText(), new java.sql.Date(cal.getDate().getTime()), 
                                String.valueOf(cmbl1.getSelectedItem()), String.valueOf(cml2.getSelectedItem()), Integer.parseInt(txtDura.getText()), 
                                Double.parseDouble(txtCos.getText()),  String.valueOf(cmbCla.getSelectedItem()),  String.valueOf(cmbCat.getSelectedItem())));
                        JOptionPane.showMessageDialog(getParent(), "SE modifico  CORRECTAMENTE", "¡ÉXITO!", JOptionPane.INFORMATION_MESSAGE);
         cal.setEnabled(true);
         txtId.setText("");
                txtTit.setText("");
                txtDesc.setText("");
                cmbl1.setSelectedIndex(0);
                cml2.setSelectedIndex(0);
                txtDura.setText("");
                txtCos.setText("");
                cmbCla.setSelectedIndex(0);
                cmbCat.setSelectedIndex(0);
        } catch (Exception e) {
                    }
        
                    }
      
                   
            }
        cargarPeliculas();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Seleccione Registro a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
        int row = Integer.parseInt(txtId.getText());
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar De forma Permanente Este Registro?","Pregunta",JOptionPane.YES_NO_CANCEL_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            try {
                FilmDAO.EliminarPelis(row);
                txtId.setText("");
                txtTit.setText("");
                txtDesc.setText("");
                cmbl1.setSelectedIndex(0);
                cml2.setSelectedIndex(0);
                txtDura.setText("");
                txtCos.setText("");
                cmbCla.setSelectedIndex(0);
                cmbCat.setSelectedIndex(0);
                txtTit.requestFocus();
                txtDesc.requestFocus();
                txtId.requestFocus();
                cal.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Registro eliminado Correctamente","Aviso",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
            }
        }
        }
        cargarPeliculas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyReleased
    cargarPeliculas();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBKeyReleased

    private void tblFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmMouseClicked
        // TODO add your handling code here:

        int select = tblFilm.rowAtPoint(evt.getPoint());   
        txtId.setText(String.valueOf(tblFilm.getValueAt(select,0)));
        txtTit.setText(String.valueOf(tblFilm.getValueAt(select,1)));
        txtDesc.setText(String.valueOf(tblFilm.getValueAt(select, 2)));
        cal.setDate((java.util.Date) tblFilm.getValueAt(select, 3));
        cmbl1.setSelectedItem(tblFilm.getValueAt(select, 4));
        cml2.setSelectedItem(tblFilm.getValueAt(select, 5));
        txtDura.setText(String.valueOf(tblFilm.getValueAt(select,6)));
        txtCos.setText(String.valueOf(tblFilm.getValueAt(select,7)));
        cmbCla.setSelectedItem(tblFilm.getValueAt(select, 8));
        cmbCat.setSelectedItem(tblFilm.getValueAt(select, 9));
        cal.setEnabled(false);
        
          
        
            
       
        
        
        
    }//GEN-LAST:event_tblFilmMouseClicked

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtDuraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuraKeyReleased
        char caracter = evt.getKeyChar(); 
        if(caracter < '0' || caracter > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(getParent(), "SOLO SE ADMITEN NUMEROS", "ERROR", JOptionPane.ERROR_MESSAGE);
		}        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuraKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal lo = new MenuPrincipal(); 
        lo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmMenu().setVisible(true);
            }
        });
    }
    public void cargarPeliculas(){
        DefaultTableModel modelo = (DefaultTableModel) tblFilm.getModel();
        modelo.setRowCount(0);
        rs = conexion.ConexionBD.Consulta("SELECT * FROM film WHERE title LIKE '"+txtB.getText()+"%' "
                + "OR language_name LIKE '"+txtB.getText()+"%'"
                + "OR category_name LIKE '"+txtB.getText()+"%'"
                + "OR rating LIKE '"+txtB.getText()+"%'");
        try {
            while (rs.next()){
                Vector v= new Vector();
                v.add(rs.getInt(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getDate(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getInt(7));
                v.add(rs.getDouble(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
               
                modelo.addRow(v);
                tblFilm.setModel(modelo);
                
            }
        } catch (SQLException e) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser cal;
    private javax.swing.JComboBox<String> cmbCat;
    private javax.swing.JComboBox<String> cmbCla;
    private javax.swing.JComboBox<String> cmbl1;
    private javax.swing.JComboBox<String> cml2;
    private javax.swing.JLabel info2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFilm;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtCos;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtDura;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTit;
    // End of variables declaration//GEN-END:variables
}
